### PR TITLE
WIP: Port to Qt 5.12

### LINKED ISSUE #5: Private APIs changed (surprise)
Arch GNU/Linux. Qt 5.11.1
```
In file included from qquicksurustyle.cpp:24:
qquicksurustyle_p.h:28:10: fatal error: QtQuickControls2/private/qquickstyleattached_p.h: No such file or directory
 #include <QtQuickControls2/private/qquickstyleattached_p.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.suru:700: .obj/qquicksurustyle.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from qquicksuruunits.cpp:2:
qquicksurustyle_p.h:28:10: fatal error: QtQuickControls2/private/qquickstyleattached_p.h: No such file or directory
 #include <QtQuickControls2/private/qquickstyleattached_p.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Full list of private APIs in Qt 5.11.1:
```
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickanimatednode_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickattachedobject_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickchecklabel_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickclippedtext_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickcolor_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickcolorimage_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickiconimage_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickiconimage_p_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickiconlabel_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickiconlabel_p_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickitemgroup_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickmnemoniclabel_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickpaddedrectangle_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickplaceholdertext_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickproxytheme_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickstyle_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickstyleplugin_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickstyleselector_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquickstyleselector_p_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquicktheme_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qquicktumblerview_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qtquickcontrols2-config_p.h
qt5-quickcontrols2 /usr/include/qt/QtQuickControls2/5.11.1/QtQuickControls2/private/qtquickcontrols2global_p.h
```

### PR DESCRIPTION
**Pull request by z3ntu**
Based on #6 

`image://` to `qrc://` change: https://github.com/qt/qtquickcontrols2/commit/9fc3659a678e6d1bd6b2514486bde1d1725963da

The rest is based on many other commits in qtquickcontrols2 :)

Please only view the changes as whole, it's supposed to be squashed

Obligatory screenshot:
image

Closes #5

### CODE REVIEW

**Comment by z3ntu** [comment]
Obligatory screenshot:
image

**Comment by cibersheep** [comment]
Ouh! 💜

**Comment by bhdouglass** [comment]
Is it possible to make this compile for both 5.9 and 5.12?

**Comment by z3ntu** [comment]
The C++ code, sure, with a lot of `#ifdef`s. The build system and QML changes, I don't think so.

I think it'd be better if we'd have Qt-version specific branches, so basically a 5.9 and a 5.12 branch for now. When 5.13 releases, add the patches required for the new Qt version there and so on.

**Comment by bhdouglass** [comment]
Ok, sounds like a plan. I'll make this into a 5.12 branch. I just worry that it'll get forgotten as development progresses.

**Pull request merged**
