### PR TITLE
Dark theme detection

### PR DESCRIPTION
**Pull request by bhdouglass**
Detect the dark theme being set in the ubuntu touch uitk's config file. Also added a clickable setup to make it easier to test on the device.

### CODE REVIEW

**Comment by cibersheep** [comment]
testing `clickable` on my N5

So, I see clickable is build Suru and pushing to `/home/phablet/` the files:
for example `push: build/tmp/usr/lib/arm-linux-gnueabihf/qt5/qml/QtQuick/Controls.2/Suru/RadioIndicator.qml -> /home/phablet/RadioIndicator.qml` asks for device password and waits.

Is this the expected behaviour?

**Comment by bhdouglass** [comment]
Yeah that's expected. It is a bit of a hack so it asks for the sudo password on the device to copy the files to the correct location. Unfortunately the password is show in clear text for some reason. It's definitely not the best solution, but it got me to be able to test easily on the device.

**Comment by cibersheep** [comment]
Not questioning :) just to know.
Also, how I use the `qt_is_dark_system_theme` in the code?

**Comment by cibersheep** [comment]
Not questioning :) just to know.
Also, how I use the `qt_is_dark_system_theme` in the code?

**Comment by bhdouglass** [comment]
It's being used in several places already, most importantly here: https://github.com/ubports/qqc2-suru-style/pull/10/files#diff-52eecf80ef8df6dcb55e84dcf9670484R397

**Comment by bhdouglass** [comment]
Closing because I made a new PR from a new branch.

**Pull request closed without merging**
