### PR TITLE
Fixed the combo box's editable state

### LINKED ISSUE #43: cannot get ComboBox editable
When setting 'editable' to true for a ComboBox it has no effect. Could it be due to the style for ComboBox using a 'Text' field which is a readonly text component?

### PR DESCRIPTION
**Pull request by bhdouglass**
Fixes #43

### CODE REVIEW

**Comment by cibersheep** [comment]
Ouh... where this came from <3?
How can I test it?

**Comment by bhdouglass** [comment]
@cibersheep I just pushed up a nasty hack to allow us to use clickable. Crossbuilder should work, but I haven't tried it in a while.

**Comment by cibersheep** [comment]
> @cibersheep I just pushed up a nasty hack to allow us to use clickable. Crossbuilder should work, but I haven't tried it in a while.

looks like it's stuck. I'll try to test this on device in these days

**Comment by bhdouglass** [comment]
@cibersheep if that doesn't work out, you can always just push the changed file to the device.

**Comment by cibersheep** [comment]
> @cibersheep if that doesn't work out, you can always just push the changed file to the device.

Yes, that's what I was thinking... I do that with Shell stuff as I found it quicker :D even more «dangerous»

**Comment by cibersheep** [comment]
Tested with the QQC2 gallery <3 it seems to behave as expected:
 - text on ComboBox is selectable and editable
 - If edited a second time, it creates another entry in the list

Before:

image

After

image 
image

**Comment by cibersheep** [comment]
@bhdouglass looks like branch building is stuck (and it's required for merging): https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fqqc2-suru-style/branches

**Comment by bhdouglass** [comment]
Maybe @UniversalSuperBox can provide some help there?

**Pull request merged**
