### PR TITLE
Fixes for Qt 5.12

### PR DESCRIPTION
**Pull request by dobey**

### CODE REVIEW

**Review by mariogrip — APPROVED** [review]

**Review by bhdouglass — CHANGES_REQUESTED** [review]
@dobey can you check this against the 5.12 branch before we merge this? I'm thinking we should merge that into xenial as well.

**Comment by UniversalSuperBox** [comment]
@bhdouglass, is that required for any release on 5.12? Right now, we're blocking rootfs builds for these PRs.

**Comment by dobey** [comment]
> @dobey can you check this against the 5.12 branch before we merge this? I'm thinking we should merge that into xenial as well.

There are some conflicting differences, but the core necessary bits are in this branch already.

**Review by bhdouglass — APPROVED** [review]
@UniversalSuperBox no it's not required, I just figured if we run into issues they could be solved in that branch. But looks like we can go ahead and just merge this one :+1:

**Pull request merged**
