### PR TITLE
Dark theme detection

### PR DESCRIPTION
**Pull request by bhdouglass**
Detect the dark theme being set in the ubuntu touch uitk's config file. Also added a clickable setup to make it easier to test on the device.

### CODE REVIEW

**Comment by cibersheep** [comment]
I can test the PR tomorrow (I think)

**Comment by cibersheep** [comment]
@bhdouglass do you need to check the building error before merging?

**Comment by bhdouglass** [comment]
This PR was made against the master branch rather than the xenial branch, not sure if that caused this issue. @UniversalSuperBox how can I restart the ci checks?

**Comment by bhdouglass** [comment]
Merging this in despite failing checks, since it works on my other PR based on this branch.

**Pull request merged**
