### PR TITLE
Add Scalable Spinner Icon

### PR DESCRIPTION
**Pull request by cibersheep**
Unable to test this before pushing :(
Could you test it before merging?

### CODE REVIEW

**Comment by bhdouglass** [comment]
@cibersheep I made a few changes, can you check them out?

**Comment by cibersheep** [comment]
Looks good to me!

**Comment by bhdouglass** [comment]
Yo @UniversalSuperBox , what's up with the build? Looks like it's got dependency issues.

**Comment by UniversalSuperBox** [comment]
The branch isn't named correctly

**Comment by bhdouglass** [comment]
oh, duh ;P

**Pull request merged**
