### PR TITLE
Add support for icons and 5.12 fixes

### PR DESCRIPTION
**Pull request by dano6**
During porting Quickddit to 5.12 I encountered a couple of issues. There wasn't support for icons, sliders was broken and Menu wasn't showing menu items.
This mr should fix that. Thanks for any feedback.

### CODE REVIEW

**Comment by dano6** [comment]
Rebased on xenial branch

**Comment by dano6** [comment]
This will break  https://gitlab.com/ubports/apps/teleports/-/blob/master/app/qml/components/MenuPanelItem.qml because of variable name icon.
It needs to be updated

**Comment by bhdouglass** [comment]
@dobey as the resident Qt 5.12 expert, do you mind taking a look?

**Comment by dobey** [comment]
> @dobey as the resident Qt 5.12 expert, do you mind taking a look?

It's on my list, but holding for now until OTA-17 is out, as we are frozen on it at the moment. I think there will be a call for testing soon.

**Comment by dobey** [comment]
> This will break https://gitlab.com/ubports/apps/teleports/-/blob/master/app/qml/components/MenuPanelItem.qml because of variable name icon.
> It needs to be updated

Is there a PR to update  it? What other apps would be broken with this? It will not be nice to knowingly land a change which breaks popular apps in the store.

**Review by dobey — DISMISSED** [review]
Marking as changes requested for previous comment, to indicate this should not be merged until TelePorts app (and possibly others) is fixed.

**Comment by dano6** [comment]
> Is there a PR to update it? What other apps would be broken with this? It will not be nice to knowingly land a change which breaks popular apps in the store.

I just created [bug report](https://gitlab.com/ubports/apps/teleports/-/issues/248), I am going to make MR for teleports.
I was testing apps more, found that it will broke Seabass2 too. No other issues found for now.

**Comment by dano6** [comment]
There is [MR](https://gitlab.com/ubports/apps/teleports/-/merge_requests/403) in Teleports, Seabass2 was fixed.

**Comment by Flohack74** [comment]
TELEports has been fixed already.

**Comment by Flohack74** [comment]
Moved this to OTA-21 due to need for extended test period. We want to release OTA-20 with minimum regression potential. This PR should be merged __early__ in the 21 cycle, though.

**Comment by Flohack74** [comment]
@dobey think its safe to merge it now

**Comment by dano6** [comment]
@Flohack74 I would love to get it merged rather early in the merging window too. It is ready for a while, I was using it without problems.

**Review by Flohack74 — APPROVED** [review]

**Comment by lduboeuf** [comment]
tested with Quickddit XperiaX: icons and menu are here

**Pull request merged**
