### PR TITLE
debian/rules: allow building with crossbuilder

### PR DESCRIPTION
**Pull request by mardy**
Remove the unnecessary QT_SELECT variable, which breaks crossbuilder.

### CODE REVIEW

**Comment by dobey** [comment]
What is the exact error with crossbuilder when using QT_SELECT, which is the correct way to be doing this (and the way most all the packages maintained by qt/kde team in debian now build)? We need a better way to solve this..

**Comment by mardy** [comment]
> What is the exact error with crossbuilder when using QT_SELECT, which is the correct way to be doing this (and the way most all the packages maintained by qt/kde team in debian now build)? We need a better way to solve this..

The error is:
```
dh build --with pkgkde_symbolshelper
   dh_testdir
   dh_update_autotools_config
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/home/mardy/qqc2-suru-style'
qmake
/home/mardy/qqc2-suru-style/.qmake.conf:1: Cannot find feature qt_build_config
Could not find qmake configuration file linux-g++.
Error processing project file: /home/mardy/qqc2-suru-style/suru.pro
debian/rules:7: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 3
make[1]: Leaving directory '/home/mardy/qqc2-suru-style'
debian/rules:4: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

The problem is that since we are cross-compiling, the `qt5` profile still points to the native host toolchain:
```
qtchooser -print-env
QT_SELECT="qt5"
QTTOOLDIR="/usr/lib/qt5/bin"
QTLIBDIR="/usr/lib/x86_64-linux-gnu"
```
The `qt5-default` package, on the other hand, installs a file `/usr/lib/<arch>/qtchooser/default.conf` which qtchooser will read with a lower priority (allowing people to override it with the `QT_SELECT` variable). So from crossbuilder we can override the `QT_SELECT` variable and set it to the right profile for cross-compilation.

**Comment by mardy** [comment]
I pushed a commit with another approach, which also works both in CI and crossbuilder.

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Pull request merged**
